# Generated by Django 3.2.5 on 2021-07-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
        migrations.RenameModel(
            old_name='MoviesMetadata',
            new_name='Movie',
        ),
    ]
