# Generated by Django 3.2.5 on 2021-07-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0004_auto_20210725_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='match_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
